### NumPy
- Numpy stands for Numerical Python.
- It is an open-source python library used for working with arrays.
- It also includes functions for working with linear algebra, the fourier transform and matrices.
- It is a completely open-source and free project.

Creating NumPy Arrays

In [9]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


0-D Arrays

In [10]:
import numpy as np
arr=np.array(42)
print(arr)

42


1-D Arrays

In [12]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


2-D Arrays

In [14]:
import numpy as np
arr=np.array([[7,8,9],[10,11,12]])
print(arr)

[[ 7  8  9]
 [10 11 12]]


3-D Arrays

In [16]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[11,12,13,14],[15,16,17,18]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]


Check Number of Dimensions

In [21]:
import numpy as np
a=np.array(34)
b=np.array([1,2,3,4])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


I/O with NumPy

In [27]:
# numpy.save() file stores the input array in a disk file with npy extension
import numpy as np
a=np.array([85,86,87,84])
np.save('numpyfile',a)

In [30]:
# To reconstruct array from numpyfile.npy us load() function
import numpy as np
b=np.load('numpyfile.npy')
print(b)

[85 86 87 84]


In [35]:
# The storage and retrieval of array data in simple text file format is done with savetxt() and loadtxt() functions.
import numpy as np
a=np.array([1,2,3,4,5])
np.savetxt('numpytxtfile.txt',a)
n=np.loadtxt('numpytxtfile.txt')
print(n)

[1. 2. 3. 4. 5.]


Indexing
- Individual elements are accessed through indexing.
- The indexing begins at zero.
- With numpy indexing, you can also extract entires rows, columns or planes from multidimensional arrays.

Indexing Using Index Arrays

In [45]:
import numpy as np
arr=np.arange(1,10,2)
print("Elements of array: ",arr)
arr2=arr[np.array([4,0,2,1,2])]
print("Indexed Elements of array arr: ",arr2)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 3 5]


Indexing in 1 Dimension

In [40]:
import numpy as np
arr=np.arange(5)
print("Array arr: ",arr)
print("Element at index 0 of arr is: ",arr[0])
print("Element at index 1 of arr is: ",arr[1])

Array arr:  [0 1 2 3 4]
Element at index 0 of arr is:  0
Element at index 1 of arr is:  1


Indexing in 2 Dimensions

In [49]:
import numpy as np
arr=np.arange(1,13)
arr2=arr.reshape(3,4)
print("Array arr2:\n",arr2)
print("Element at 0th row and 0th column of arr2 is: ",arr2[0][0])
print("Element at 1nd row and 2nd column of arr2 is: ",arr2[1][2])

Array arr2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at 0th row and 0th column of arr2 is:  1
Element at 1nd row and 2nd column of arr2 is:  7


Indexing in 3 Dimensions

In [52]:
import numpy as np
arr=np.arange(12)
arr2=arr.reshape(2,2,3)
print("Array arr2:\n",arr2)
print("Element: ",arr2[1,1,2])

Array arr2:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element:  11


Slicing an Array
- To access elements from numpy array in specific range, use numpy indexing.
- A subtuple, substring, or sublist is produced from a tuple, string, or list respectively.
- The same principles that apply to python lists also apply to numpy arrays when it comes to slicing.

Slicing 1-D Array

In [56]:
import numpy as np
arr=np.arange(6)
print("Array arr: ",arr)
print("Sliced element of array: ",arr[1:4])

Array arr:  [0 1 2 3 4 5]
Sliced element of array:  [1 2 3]


Slicing 2-D Arrays

In [64]:
import numpy as np
arr=np.arange(12)
arr2=arr.reshape(3,4)
print("Array arr: \n",arr2)
print("\n")
print("Element of 1st row and 1st column upto last column \n",arr2[1:,1:4])

Array arr: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Element of 1st row and 1st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]


Broadcasting
- Broadcasting explains the way NumPy handles arrays of various shapes when performing arithmetic operations

In [72]:
import numpy as np
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])

print("First array: ")
print(a)
print("Dimension of first array:",a.ndim)
print("\n")

print("Second array: ")
print(b)
print("Dimension of second array:",b.ndim)
print("\n")

print("First Array + Second Array:-")
print(a+b)


First array: 
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Dimension of first array: 2


Second array: 
[1. 2. 3.]
Dimension of second array: 1


First Array + Second Array:-
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


Structured Arrays
- Various types and sizes of data are organised using it.

In [76]:
# Structured array
import numpy as np
a=np.array([('Devin',15,20.5),('James',56,58.5),('Lara',43,40.3),(123,52,54.6)],dtype=[('name',(np.str_,15)),('age',np.int32),('weight',np.float64)])
print(a)
print(a["name"])
print(a["age"])
print(a["weight"])

[('Devin', 15, 20.5) ('James', 56, 58.5) ('Lara', 43, 40.3)
 ('123', 52, 54.6)]
['Devin' 'James' 'Lara' '123']
[15 56 43 52]
[20.5 58.5 40.3 54.6]


Statistical Functions

In [87]:
import numpy as np
arr=np.arange(1,16)
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.amax(arr))
print(np.amin(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,50))
print(np.average(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
8.0
8.0
15
1
4.320493798938574
18.666666666666668
8.0
8.0


In [90]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [96]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
# Warning on division by zero but not an error just replaced with nan
a=np.array([1,2,3,4,5])
b=np.array([1,0,1,0,1])
a/b

C:\Users\Dishang\AppData\Local\Temp\ipykernel_10572\351103285.py:4: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 1., inf,  3., inf,  5.])

In [102]:
# Also warning but not an error instead infinity
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667])

In [106]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331,
       1728, 2197, 2744, 3375], dtype=int32)